"""add_is_active_to_customers

Revision ID: 9a97d2e7fc4a
Revises: bf6060557867
Create Date: 2026-09-22 10:28:29.695826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a97d2e7fc4a'
down_revision: Union[str, Sequence[str], None] = 'bf6060557867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_active')
    # ### end Alembic commands ###
