"""baseline schema

Revision ID: bb636ea3a4c5
Revises: 
Create Date: 2026-09-27 07:49:16.412124
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb636ea3a4c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_log_changed_at', ['changed_at'], unique=False)
        batch_op.create_index('ix_audit_log_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_customers_name', ['name'], unique=False)
        batch_op.create_index('uq_customers_phone_active', ['phone'], unique=True, sqlite_where=sa.text('is_active = 1'))

    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.Enum('RAW', 'PACKAGING', name='ingredientkind'), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reorder_threshold', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.create_index('ix_ingredients_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_ingredients_kind', ['kind'], unique=False)
        batch_op.create_index('uq_ingredients_name_active', ['name'], unique=True, sqlite_where=sa.text('is_active = 1'))

    op.create_table('number_sequences',
    sa.Column('prefix', sa.String(length=40), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('prefix')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('measure_value', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('measure_unit', sa.String(length=10), nullable=True),
    sa.Column('pack_size', sa.Integer(), nullable=False),
    sa.Column('pack_label', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('prep_time_hours', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('ix_products_category', ['category'], unique=False)
        batch_op.create_index('ix_products_is_active', ['is_active'], unique=False)
        batch_op.create_index('uq_products_sku_active', ['sku'], unique=True, sqlite_where=sa.text('is_active = 1'))

    op.create_table('addresses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index('ix_addresses_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_addresses_is_active', ['is_active'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INQUIRY', 'CONFIRMED', 'IN_PROGRESS', 'READY', 'DELIVERED', 'PAID', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('fulfillment_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_type', sa.String(length=10), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('ix_orders_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_orders_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_orders_fulfillment_date', ['fulfillment_date'], unique=False)
        batch_op.create_index('ix_orders_order_date', ['order_date'], unique=False)
        batch_op.create_index('ix_orders_status', ['status'], unique=False)

    op.create_table('product_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'ingredient_id', name='uq_product_ingredient')
    )
    with op.batch_alter_table('product_ingredients', schema=None) as batch_op:
        batch_op.create_index('ix_product_ingredients_ingredient', ['ingredient_id'], unique=False)
        batch_op.create_index('ix_product_ingredients_product', ['product_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.Enum('PURCHASE', 'CONSUMPTION', 'WASTAGE', 'RETURN', 'ADJUSTMENT', name='movementreason'), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('unit_cost_at_time', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('total_cost_at_time', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movements_ingredient', ['ingredient_id', 'created_at'], unique=False)
        batch_op.create_index('ix_stock_movements_reason', ['reason'], unique=False)
        batch_op.create_index('ix_stock_movements_reference', ['reference_type', 'reference_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_address', sa.Text(), nullable=False),
    sa.Column('business_phone', sa.String(length=50), nullable=False),
    sa.Column('business_email', sa.String(length=100), nullable=False),
    sa.Column('business_gstin', sa.String(length=20), nullable=False),
    sa.Column('business_fssai', sa.String(length=20), nullable=False),
    sa.Column('billed_to_name', sa.String(length=100), nullable=False),
    sa.Column('billed_to_phone', sa.String(length=20), nullable=False),
    sa.Column('billed_to_email', sa.String(length=100), nullable=False),
    sa.Column('billed_to_address', sa.Text(), nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('fulfillment_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_type', sa.String(length=10), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gst_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('advance_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_items_json', sa.Text(), nullable=False),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_invoice_date', ['invoice_date'], unique=False)
        batch_op.create_index('ix_invoices_order_id', ['order_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('customization_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index('ix_order_items_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_order_items_product_id', ['product_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_order_id', ['order_id'], unique=False)
        batch_op.create_index('ix_payments_received_at', ['received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_received_at')
        batch_op.drop_index('ix_payments_order_id')

    op.drop_table('payments')
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index('ix_order_items_product_id')
        batch_op.drop_index('ix_order_items_order_id')

    op.drop_table('order_items')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_order_id')
        batch_op.drop_index('ix_invoices_invoice_date')

    op.drop_table('invoices')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_reference')
        batch_op.drop_index('ix_stock_movements_reason')
        batch_op.drop_index('ix_stock_movements_ingredient')

    op.drop_table('stock_movements')
    with op.batch_alter_table('product_ingredients', schema=None) as batch_op:
        batch_op.drop_index('ix_product_ingredients_product')
        batch_op.drop_index('ix_product_ingredients_ingredient')

    op.drop_table('product_ingredients')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_status')
        batch_op.drop_index('ix_orders_order_date')
        batch_op.drop_index('ix_orders_fulfillment_date')
        batch_op.drop_index('ix_orders_customer_id')
        batch_op.drop_index('ix_orders_created_at')

    op.drop_table('orders')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index('ix_addresses_is_active')
        batch_op.drop_index('ix_addresses_customer_id')

    op.drop_table('addresses')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('uq_products_sku_active', sqlite_where=sa.text('is_active = 1'))
        batch_op.drop_index('ix_products_is_active')
        batch_op.drop_index('ix_products_category')

    op.drop_table('products')
    op.drop_table('number_sequences')
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_index('uq_ingredients_name_active', sqlite_where=sa.text('is_active = 1'))
        batch_op.drop_index('ix_ingredients_kind')
        batch_op.drop_index('ix_ingredients_is_active')

    op.drop_table('ingredients')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('uq_customers_phone_active', sqlite_where=sa.text('is_active = 1'))
        batch_op.drop_index('ix_customers_name')
        batch_op.drop_index('ix_customers_is_active')

    op.drop_table('customers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_entity')
        batch_op.drop_index('ix_audit_log_changed_at')
        batch_op.drop_index('ix_audit_log_action')

    op.drop_table('audit_log')
    # ### end Alembic commands ###